apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth-container
        image: nginx
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: controller-level-secret
              key: api-token